dataframes:
  data_EB:
    df_data_EB_Iso_train.h5
  data_EE:
    df_data_EE_Iso_train.h5
  mc_EB:
    df_mc_EB_Iso_train.h5
  mc_EE:
    df_mc_EE_Iso_train.h5

variables:
  ['probePhoIso']

year:
  2018

workDir:
  /eos/user/c/chuw/Hgg_mass/TnP/

weightsDir:
  /eos/user/c/chuw/Hgg_mass/PhI/
