dataframes:
  data:
    EB:
      input: df_data_EB_test.h5
      output: df_data_EB_test_IdMVA_5M.h5
    EE:
      input: df_data_EE_test.h5
      output: df_data_EE_test_IdMVA_5M.h5
  mc:
    EB:
      #input: df_mc_EB_test_clf.h5
      input: df_mc_EB_test.h5
      output: df_mc_EB_test_corr_clf_5M.h5
    EE:
      #input: df_mc_EE_test_clf.h5
      input: df_mc_EE_test.h5
      output: df_mc_EE_test_corr_clf_5M.h5

showerShapes:
  ['probeCovarianceIeIp','probeS4','probeR9','probePhiWidth','probeSigmaIeIe','probeEtaWidth']

chIsos:
  ['probeChIso03','probeChIso03worst']

year:
  2017

workDir:
  /work/gallim/dataframes

weightsDirs:
  showerShapes:
    /work/gallim/weights/2017/old_style
  phoIso:
    /work/gallim/weights/2017/old_style
  chIsos:
    /work/gallim/weights/2017/old_style

finalWeightsDirs:
  showerShapes:
    /work/gallim/dataframes/weights_dask/final
  phoIso:
    /work/gallim/dataframes/weights_dask/final
  chIsos:
    /work/gallim/dataframes/weights_dask/final
